export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_INVENTORY = 'GET_INVENTORY';
export const SHOW_MODAL = 'SHOW_MODAL';
export const LOADING_INVENTORY = 'LOADING_INVENTORY';
